### ISSUE TITLE
Receive: netlink receive: operation not supported

### ISSUE THREAD

**Issue by DFS-90** [theseal/addons-homeassistant#1]
Hi,

I tried to install your wireguard-ui-addon on HomeAssistant.

Unfortunately; I can't start it properly (see protocol).
Do you have any idea how to fix this?

Thanks in advance,
David

---

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Wireguard UI
 Web UI for provisioning and managing device keys and configurations for Wireguard.
-----------------------------------------------------------
 Add-on version: 1.0.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.3.5
 Home Assistant Supervisor: 2022.03.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[01:43:58] INFO: Starting Wireguard UI...
[01:43:58] INFO: Starting NGinx...
time="2022-03-18T01:43:58+01:00" level=info msg=Starting
time="2022-03-18T01:43:58+01:00" level=debug msg="ipAddr: 172.31.255.0  ipNet: 172.31.255.0/24"
time="2022-03-18T01:43:58+01:00" level=debug msg="Read server config from file: /data/config.json"
time="2022-03-18T01:43:58+01:00" level=debug msg="Configuration loaded with public key: <KEY REMOVED>
[favicon.png index.html main.css main.css.map main.js main.js.map vendors~main.1.js vendors~main.1.js.map vendors~main.css vendors~main.css.map] <nil>
time="2022-03-18T01:43:58+01:00" level=debug msg="Server initialized: /data"
time="2022-03-18T01:43:58+01:00" level=debug msg="Adding wireguard device: wg0"
time="2022-03-18T01:43:58+01:00" level=debug msg="Adding ip address to wireguard device: 172.31.255.0/24"
time="2022-03-18T01:43:58+01:00" level=debug msg="Bringing up wireguard device: wg0"
time="2022-03-18T01:43:58+01:00" level=debug msg="Adding NAT / IP masquerading using nftables"
time="2022-03-18T01:43:58+01:00" level=debug msg="Flushing nftable rulesets"
time="2022-03-18T01:43:58+01:00" level=debug msg="Setting up nftable rules for ip masquerading"
time="2022-03-18T01:43:58+01:00" level=fatal msg="Receive: netlink receive: operation not supported"
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by theseal** [comment]
That seems weird. I just upgraded my installation (Pi) to the same version you are using and it works just fine. 

Not sure what (amd64 / qemux86-64) means in your output. How do you run your Home Assistant OS?

**Comment by DFS-90** [comment]
I’m running HA OS on ESXi as described here:
https://www.home-assistant.io/installation/alternative

 
It’s a „full“ vm, no LXC used.

I installed the .ova file and made sure the “E1001” or “E1001E” virtual network adapter was used.

 
Do you have any idea what causes the trouble?

 
Thanks in advance,

David

 
Von: Johan Wassberg ***@***.***>
Gesendet: Samstag, 19. März 2022 13:35
An: theseal/addons-homeassistant ***@***.***>
Cc: DFS-90 ***@***.***>; Author ***@***.***>

Betreff: Re: [theseal/addons-homeassistant] Receive: netlink receive: operation not supported (Issue #1)

 
That seems weird. I just upgraded my installation (Pi) to the same version you are using and it works just fine.

Not sure what (amd64 / qemux86-64) means in your output. How do you run your Home Assistant OS?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by theseal** [comment]
Then I would guess that your NIC isn't named eth0 as on a PI. Could you confirm? Should be stated on the start view of the Terminal addon.

**Comment by DFS-90** [comment]
You’re right – my NIC is named enp2s1.

 
Do you think it’s possible to add a configuration option for the Wireguard UI add-on where the name of the interface can be set?

 
Thanks for your support,

David

 
Von: Johan Wassberg ***@***.***>
Gesendet: Samstag, 19. März 2022 15:54
An: theseal/addons-homeassistant ***@***.***>
Cc: DFS-90 ***@***.***>; Author ***@***.***>

Betreff: Re: [theseal/addons-homeassistant] Receive: netlink receive: operation not supported (Issue #1)

 
Then I would guess that your NIC isn't named eth0 as on a PI. Could you confirm? Should be stated on the start view of the Terminal addon.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by theseal** [comment]
I think I managed to fix the issue in a dynamic way i 1.0.4. Could you give it a try?

**Comment by DFS-90** [comment]
Thanks a lot – unfortunately, it still doesn’t work.

Please see attached log file.

 
I completely uninstalled the add-on and re-installed v1.0.4; I also did a rebuild.

 
Von: Johan Wassberg ***@***.***>
Gesendet: Sonntag, 20. März 2022 08:54
An: theseal/addons-homeassistant ***@***.***>
Cc: DFS-90 ***@***.***>; Author ***@***.***>

Betreff: Re: [theseal/addons-homeassistant] Receive: netlink receive: operation not supported (Issue #1)

 
I think I managed to fix the issue in a dynamic way i 1.0.4. Could you give it a try?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: Wireguard UI
 Web UI for provisioning and managing device keys and configurations for Wireguard.
-----------------------------------------------------------
 Add-on version: 1.0.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 7.5  (amd64 / qemux86-64)
 Home Assistant Core: 2022.3.5
 Home Assistant Supervisor: 2022.03.5
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] nginx.sh: executing... 
[cont-init.d] nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:25:13] INFO: Starting Wireguard UI...
[12:25:13] INFO: Starting NGinx...
time="2022-03-20T12:25:13+01:00" level=info msg=Starting
time="2022-03-20T12:25:13+01:00" level=debug msg="ipAddr: 172.31.255.0  ipNet: 172.31.255.0/24"
time="2022-03-20T12:25:13+01:00" level=debug msg="Read server config from file: /data/config.json"
time="2022-03-20T12:25:13+01:00" level=debug msg="Configuration loaded with public key: qdval00d0EXwZ5DlrUXqaAal2riCTVNkfDxkHE6y/Wk="
[favicon.png index.html main.css main.css.map main.js main.js.map vendors~main.1.js vendors~main.1.js.map vendors~main.css vendors~main.css.map] <nil>
time="2022-03-20T12:25:13+01:00" level=debug msg="Server initialized: /data"
time="2022-03-20T12:25:13+01:00" level=debug msg="Adding wireguard device: wg0"
time="2022-03-20T12:25:13+01:00" level=debug msg="Adding ip address to wireguard device: 172.31.255.0/24"
time="2022-03-20T12:25:13+01:00" level=debug msg="Bringing up wireguard device: wg0"
time="2022-03-20T12:25:13+01:00" level=debug msg="Adding NAT / IP masquerading using nftables"
time="2022-03-20T12:25:13+01:00" level=debug msg="Flushing nftable rulesets"
time="2022-03-20T12:25:13+01:00" level=debug msg="Setting up nftable rules for ip masquerading"
time="2022-03-20T12:25:13+01:00" level=fatal msg="Receive: netlink receive: operation not supported"
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
s6-nuke: fatal: unable to kill: No such process

**Comment by theseal** [comment]
Next guess is that there are no nftable support in your image. Is it possible to enable SSH debug in the ESXi setup? https://developers.home-assistant.io/docs/operating-system/debugging/

If so what does `lsmod | grep nft` say?

**Comment by DFS-90** [comment]
I was unable to run lsmod on the ESXi server's SSH shell.
Still, it worked on the VMWare console of HA OS - please see attached screenshot.

<img width="444" alt="Screenshot" src="https://user-images.githubusercontent.com/87578070/159721321-9d38912e-9297-472d-8776-f0fc51437ad7.png">
.

**Comment by theseal** [comment]
Cool. Seems like nftables is missing.

Don't think I can do anything with the addon to fix this but I created a issue with a request for future support of nftables.
https://github.com/home-assistant/operating-system/issues/1812

**Comment by DFS-90** [comment]
Okay, thanks for your investigations! I'll have a look at your request and try again when an updated image with nftables support is available.

Until then, I will be able to use the wireguard add-on without UI as this works OOTB.
Do you know the difference? Does the OOTB wireguard add-on work without nftables?

Thanks a lot,
David

**Comment by theseal** [comment]
The GUI-less wireguard addon seems to use iptables instead of nftables.

**Comment by DFS-90** [comment]
Updated image is available, problem is solved.
